<a href="https://colab.research.google.com/github/eunsg1/2026/blob/main/BDA/03w_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print(np.linspace(2, 3))

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]


In [2]:
print(np.linspace(2, 3, retstep = True))

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]), np.float64(0.02040816326530612))


In [3]:
print((3 - 2) / (50 - 1))

0.02040816326530612


In [4]:
print(np.linspace(2, 3, endpoint = False, retstep = True))

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
       2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
       2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
       2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]), np.float64(0.02))


In [6]:
print((3 - 2) / 50)

0.02


In [7]:
np.linspace(2, 3, num = 5, retstep = False)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [8]:
np.linspace(2, 3, num = 5, endpoint = False, retstep = True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

# numpy 주요 함수

In [16]:
print(np.zeros(5))
print(np.zeros(5).dtype)
print(np.zeros(5, dtype = int))
print(np.zeros((2, 3)))
print(np.zeros(2, 3))

[0. 0. 0. 0. 0.]
float64
[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


TypeError: Cannot interpret '3' as a data type

In [20]:
print(np.full((2, 3), 10))
print(np.full([2, 3], [1, 2, 3]))
print(np.full([2, 3], [1, 2]))

[[10 10 10]
 [10 10 10]]
[[1 2 3]
 [1 2 3]]


ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [21]:
print(np.full([3, 4], range(4)))

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [23]:
print(np.full([4, 3], fill_value = np.arange(4).reshape(4, 1)))
print(np.arange(4).reshape(4, 1))

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
[[0]
 [1]
 [2]
 [3]]


In [30]:
a = np.arange(6).reshape(3, 2)
b = np.array([[1], [2]])

print(a)
print(b)
print(a @ b)

[[0 1]
 [2 3]
 [4 5]]
[[1]
 [2]]
[[ 2]
 [ 8]
 [14]]


In [56]:
a = np.arange(1, 25).reshape(2, 3, 4)
print(a)


print(a[0, 2, 3])

print(a.ravel())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
12
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [69]:
a = np.arange(1, 4).reshape(1, 3)
b = np.arange(1, 4).reshape(3, 1)

print(a)
print(b)
print(a * b)

[[1 2 3]]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


# 고급 색인

In [77]:
x = np.arange(1, 11)
print(x)

print(x[1])
print(x[:5])
print(x[[2]])
print(x[[2, 3]])
print(x[[2, 3, 5, 8]])
print(x[np.array([5, 3, -4, 8])])

[ 1  2  3  4  5  6  7  8  9 10]
2
[1 2 3 4 5]
[3]
[3 4]
[3 4 6 9]
[6 4 7 9]


In [78]:
x = np.arange(1, 57).reshape(7, 8)
print(x)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]]


In [84]:
print(x[0])
print(x[0, 1])
print(x[:, 2:8])
#x[, 2:8]

print(x[[0], [1]])
print(x[0, 1])

print(x[:, [5, 4]])
print(x[[1, 3]])
print(x[[1, 3], :])

[1 2 3 4 5 6 7 8]
2
[[ 3  4  5  6  7  8]
 [11 12 13 14 15 16]
 [19 20 21 22 23 24]
 [27 28 29 30 31 32]
 [35 36 37 38 39 40]
 [43 44 45 46 47 48]
 [51 52 53 54 55 56]]
[2]
2
[[ 6  5]
 [14 13]
 [22 21]
 [30 29]
 [38 37]
 [46 45]
 [54 53]]
[[ 9 10 11 12 13 14 15 16]
 [25 26 27 28 29 30 31 32]]
[[ 9 10 11 12 13 14 15 16]
 [25 26 27 28 29 30 31 32]]


In [87]:
print(x[[1, 3], [2, 2]])
print(x[[1, 3], [2]])
print(x[[1, 3], 2])

[11 27]
[11 27]
[11 27]


In [92]:
print(x[np.array([0, 2, 4]), 1])
print(x[[0, 2, 4], 1])
print(x[[0, 2, 4], :2])


[ 2 18 34]
[ 2 18 34]
[[ 1  2]
 [17 18]
 [33 34]]


In [97]:
print(x[[0, 2, 4], [0, 1]])
print(x[np.array(0, 2, 4), np.array(0, 1)])

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [105]:
a = np.arange(1, 41).reshape(5, 8)
print(a)
print(a[2:4, 3:7])
print(a[np.arange(2, 4)])

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]
[[20 21 22 23]
 [28 29 30 31]]
[[17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [114]:
print(a[np.arange(2, 4)][:, [1, 0]])
print(a[np.arange(2, 5)][:, [1, 0, 3, 5]])
print(a[np.arange(2, 5)])
print(a[np.arange(2, 5)][:, np.arange(-1, -8, -1)])

[[18 17]
 [26 25]]
[[18 17 20 22]
 [26 25 28 30]
 [34 33 36 38]]
[[17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]
[[24 23 22 21 20 19 18]
 [32 31 30 29 28 27 26]
 [40 39 38 37 36 35 34]]
