<a href="https://colab.research.google.com/github/eunsg1/2026/blob/main/BDA/04w_array_stack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np

a = np.arange(6).reshape(3, 2)
print(a)

b = np.arange(6, 12).reshape(3, 2)
print(b)

print(np.hstack((a, b)))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [34]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

In [37]:
a = np.arange(6).reshape(3, 2)
print(a)

b = np.arange(10, 19).reshape(3, 3)
print(b)

print(np.hstack((a, b)))

[[0 1]
 [2 3]
 [4 5]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 0  1 10 11 12]
 [ 2  3 13 14 15]
 [ 4  5 16 17 18]]


In [41]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print(np.column_stack((x, y)))
print(np.column_stack((x[:, np.newaxis], y[:, np.newaxis])))

print(x[:, np.newaxis])
print(x.shape, x[:, np.newaxis].shape)
print(np.hstack((x, y)))
print(np.column_stack == np.hstack)

[[ 1 10]
 [ 2 20]
 [ 3 30]]
[[ 1 10]
 [ 2 20]
 [ 3 30]]
[[1]
 [2]
 [3]]
(3,) (3, 1)
[ 1  2  3 10 20 30]
False


In [42]:
a = np.arange(6).reshape(2, 3)
print(a)

b = np.arange(10, 22).reshape(4, 3)
print(b)

print(np.row_stack((a, b)))

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


/tmp/ipykernel_448/3250452024.py:7: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [44]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

print(np.concatenate((a, b, c)))
print(np.concatenate((a, b, c), axis = 0))
print(np.concatenate((a, b, c), axis = None))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [50]:
x = np.arange(6).reshape(2, 3)
print(x)

y = np.arange(10, 16).reshape(2, 3)
print(y)

z = np.arange(20, 24).reshape(2, 2)
print(z)

print(np.concatenate((x, y)))
print(np.concatenate((x, y), axis = 1))
print(np.concatenate((x, y, z), axis = 1))
print(np.concatenate((x, y), axis = None))

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21]
 [22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]
[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]
[ 0  1  2  3  4  5 10 11 12 13 14 15]


In [54]:
a = np.array([1, 2, 3])
print(a)

b = np.array([4, 5, 6])
print(b)

print(np.stack((a, b)))
print(np.stack((a, b), axis = 1))
print(np.stack((a, b), axis = -1))

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [57]:
print(np.arange(1, 19).reshape(3, 3, 2))
print(np.arange(16).reshape(2, 2, 4))

x = np.arange(6).reshape(2, 3)
print(x)
y = np.arange(10, 16).reshape(2, 3)
print(y)
z = np.arange(20, 26).reshape(2, 3)
print(z)

ax0 = np.stack((x, y, z), axis = 0)
print(ax0)
print(ax0.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21 22]
 [23 24 25]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
(3, 2, 3)


In [58]:
ax1 = np.stack((x, y, z), axis = 1)
print(ax1)
print(ax1.shape)

[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
(2, 3, 3)


In [59]:
ax2 = np.stack((x, y, z), axis = 2)
print(ax2)
print(ax2.shape)

[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]
(2, 3, 3)


In [62]:
a = np.arange(1, 13).reshape(3, 4)
c = np.array([1, 3, 5])

print(np.hstack((a, np.expand_dims(c, axis = 1))))
print(np.column_stack((a, c)))

[[ 1  2  3  4  1]
 [ 5  6  7  8  3]
 [ 9 10 11 12  5]]
[[ 1  2  3  4  1]
 [ 5  6  7  8  3]
 [ 9 10 11 12  5]]


In [64]:
print(a)
b = np.arange(1, 5)
print(b)

print(np.row_stack((a, b)))
print(np.vstack((a, b)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


/tmp/ipykernel_448/1457306026.py:5: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [70]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)
print(np.c_[a, b])
print(np.column_stack((a, b)))


[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [71]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

print(np.c_[x, 10, 20, y])
print(np.column_stack((x, 10, 20, y)))

[[ 1  2  3 10 20  4  5  6]]
[[ 1  2  3 10 20  4  5  6]]


In [72]:
print(np.r_[a, b])
print(np.hstack((a, b)))
print(np.row_stack((a, b)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


/tmp/ipykernel_448/2198860227.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [74]:
print(np.r_[a, 0, 0, b])
print(np.r_[3: 10: 3, [0] * 2, 5, 6])
print(np.r_[-1: 1: 6], [0] * 2, 5, 6)
print(np.linspace(-1, 1, 6))

[1 2 3 0 0 4 5 6]
[3 6 9 0 0 5 6]
[-1] [0, 0] 5 6
[-1.  -0.6 -0.2  0.2  0.6  1. ]


In [75]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

print(np.r_[a, a, a])
print(np.r_['0', a, a])
print(np.r_['-1', a, a])
print(np.r_['1', a, a])

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [76]:
print(np.r_['0, 2', a, a])
print(np.r_['0, 2', [1, 2, 3], [4, 5, 6]])
print(np.r_['0, 3', [1, 2, 3], [4, 5, 6]])

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [77]:
arr = np.array([1, 2, 3])
print(arr[np.newaxis, :])
print(arr[np.newaxis, :].shape, '\n')
print(arr[:, np.newaxis])
print(arr[:, np.newaxis].shape)

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1)


In [78]:
print(np.r_[[1, 2, 3], [4, 5, 6]])
print(np.r_['0, 2, 0', [1, 2, 3], [4, 5, 6]])
print(np.r_['1, 2, 0', [1, 2, 3], [4, 5, 6]])
print(np.r_['0, 2, 1', [1, 2, 3], [4, 5, 6]])
print(np.r_['1, 2, 1', [1, 2, 3], [4, 5, 6]])

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [82]:
a = np.array([1, 2, 3])
print(a.shape)

print(np.expand_dims(a, axis = (0, 1)))
print(np.expand_dims(a, axis = (0, 1)).shape)
print(np.expand_dims(a, axis = (0, 2)))
print(np.expand_dims(a, axis = (0, 2)).shape)
print(np.expand_dims(a, axis = (1, 2)))
print(np.expand_dims(a, axis = (1, 2)).shape)

(3,)
[[[1 2 3]]]
(1, 1, 3)
[[[1]
  [2]
  [3]]]
(1, 3, 1)
[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)


In [83]:
print(np.expand_dims(np.array([1, 2, 3]), axis = (1, 2)))
print(np.expand_dims(np.array([4, 5, 6]), axis = (1, 2)))
print(np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]])
print(np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape)

[[[1]]

 [[2]]

 [[3]]]
[[[4]]

 [[5]]

 [[6]]]
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]
(6, 1, 1)


In [85]:
print(np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]])
print(np.expand_dims(np.array([1, 2, 3]), axis = (0, 2)))
print(np.expand_dims(np.array([4, 5, 6]), axis = (0, 1)))
print(np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[1]
  [2]
  [3]]]
[[[4 5 6]]]
(2, 3, 1)


In [86]:
print(np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]])
print(np.expand_dims(np.array([1, 2, 3]), axis = (0, 1)))
print(np.expand_dims(np.array([4, 5, 6]), axis = (0, 1)))
print(np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]].shape)

[[[1 2 3]]

 [[4 5 6]]]
[[[1 2 3]]]
[[[4 5 6]]]
(2, 1, 3)


In [87]:
a = np.matrix('1 2; 3 4')
print(a)
print(type(a))
b = np.matrix([[1, 3], [3, 2]])
print(b)
print(a * b)
print(a @ b)

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[1 3]
 [3 2]]
[[ 7  7]
 [15 17]]
[[ 7  7]
 [15 17]]


In [89]:
print(np.r_[[[1, 2, 3]], [[4, 5, 6]]])
print(np.r_['c', [[1, 2, 3]], [[4, 5, 6]]])
print(np.r_[[1, 2, 3], [4, 5, 6]])
print(np.r_['r', [1, 2, 3], [4, 5, 6]])
print(np.r_[[1, 2, 3], [4, 5, 6]])
np.r_['c', [1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [90]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))
print(np.r_[a, b])
print(np.concatenate((a, b)))
print(np.c_[a, b])

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [91]:
print(np.vstack((a, b)))
print(np.row_stack((a, b)))
print(np.r_['0, 2', a, b])
print(np.r_[a[np.newaxis, :], b[np.newaxis, :]])
print(np.concatenate((a[np.newaxis, :], b[np.newaxis, :])))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


/tmp/ipykernel_448/1473346158.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [93]:
print(np.column_stack((a, b)))
print(np.hstack((a[:, np.newaxis], b[:, np.newaxis])))
print(np.c_[a, b])
print(np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis = 1))

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [96]:
x = np.arange(9.0)
print(x)
s = np.split(x, 3)
print(s)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]


In [99]:
y = np.arange(10, 61, 10)
print(y)

print(np.split(y, [2, 3, 4, 6]))

x = np.arange(1, 10)
print(x)
print(np.split(x, [2, 6]))

[10 20 30 40 50 60]
[array([10, 20]), array([30]), array([40]), array([50, 60]), array([], dtype=int64)]
[1 2 3 4 5 6 7 8 9]
[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


In [100]:
a = np.arange(24).reshape(2, 12)
print(a)

print(np.hsplit(a, 3))
print(np.split(a, 3, axis = 1))
print(np.split(a, 4, axis = 1))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]
[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]
[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4,  5],
       [15, 16, 17]]), array([[ 6,  7,  8],
       [18, 19, 20]]), array([[ 9, 10, 11],
       [21, 22, 23]])]


In [101]:
b = np.arange(24).reshape(6, 4)
print(b)
print(np.split(b, 3, axis = 0))
print(np.split(b, [2, 4, 6], axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]]), array([], shape=(0, 4), dtype=int64)]


In [103]:
a = np.arange(24).reshape(2, 12)
print(a)
print(np.split(a, [3, 5, 7], axis = 1))

b = np.arange(24).reshape(6, 4)
print(b)
print(np.split(b, 3, axis = 0))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4],
       [15, 16]]), array([[ 5,  6],
       [17, 18]]), array([[ 7,  8,  9, 10, 11],
       [19, 20, 21, 22, 23]])]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


In [104]:
a = np.arange(10)
print(a)
print(np.hsplit(a, 2))
print(np.hsplit(a, [2, 5]))

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]


In [105]:
a = np.arange(24).reshape(2, 12)
print(a)
print(np.hsplit(a, (3, 5, 8)))
print(a[:, :3])
print(a[:, 8:])

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4],
       [15, 16]]), array([[ 5,  6,  7],
       [17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]
[[ 0  1  2]
 [12 13 14]]
[[ 8  9 10 11]
 [20 21 22 23]]


In [106]:
a = np.arange(18).reshape(6, 3)
print(a)
print(np.vsplit(a, 3))
print(np.vsplit(a, 4))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


ValueError: array split does not result in an equal division

In [108]:
a = np.arange(18).reshape(6, 3)
print(a)

print(np.vsplit(a, (1, 4, 6)))
print(a[:1, :])
print(a[4: 6, :])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2]]), array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]]), array([], shape=(0, 3), dtype=int64)]
[[0 1 2]]
[[12 13 14]
 [15 16 17]]


In [109]:
x = np.arange(32).reshape(4, 4, 2)
print(x)

print(np.split(x, 2, axis = 0))
print(np.vsplit(x, 2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]
[array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]]), array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])]
[array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]]), array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])]


In [110]:
print(np.vsplit(x, [1, 3]))
print(x[:1, :, :])
print(x[1: 3])
print(x[3: ])

[array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]]), array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]]), array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])]
[[[0 1]
  [2 3]
  [4 5]
  [6 7]]]
[[[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[24 25]
  [26 27]
  [28 29]
  [30 31]]]


In [111]:
print(np.hsplit(x, 2))

[array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]]), array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])]


In [112]:
print(np.hsplit(x, [1, 3]))

[array([[[ 0,  1]],

       [[ 8,  9]],

       [[16, 17]],

       [[24, 25]]]), array([[[ 2,  3],
        [ 4,  5]],

       [[10, 11],
        [12, 13]],

       [[18, 19],
        [20, 21]],

       [[26, 27],
        [28, 29]]]), array([[[ 6,  7]],

       [[14, 15]],

       [[22, 23]],

       [[30, 31]]])]


In [113]:
x = np.arange(9.0)
print(x)

print(np.array_split(x, 2))
print(np.array_split(x, 3))
print(np.array_split(x, 4))
print(np.array_split(x, 5))
print(np.array_split(x, [2, 4, 8]))

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]
[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]
[array([0., 1.]), array([2., 3.]), array([4., 5.]), array([6., 7.]), array([8.])]
[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]


In [114]:
a = np.arange(35).reshape(7, 5)
print(a)

print(np.array_split(a, 2, axis = 0))
print(np.array_split(a, 2, axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])]
[array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22],
       [25, 26, 27],
       [30, 31, 32]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29],
       [33, 34]])]


In [115]:
print(np.array_split(a, [2, 4], axis = 0))
print(np.array_split(a, [2, 4], axis = 1))

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])]
[array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21],
       [25, 26],
       [30, 31]]), array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23],
       [27, 28],
       [32, 33]]), array([[ 4],
       [ 9],
       [14],
       [19],
       [24],
       [29],
       [34]])]


In [116]:
x = np.arange(24).reshape(2, 2, 6)
print(x)

print(np.array_split(x, 4, axis = 2))
print(np.dsplit(x, 2))
print(np.split(x, 2, axis = 2))

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
[array([[[ 0,  1],
        [ 6,  7]],

       [[12, 13],
        [18, 19]]]), array([[[ 2,  3],
        [ 8,  9]],

       [[14, 15],
        [20, 21]]]), array([[[ 4],
        [10]],

       [[16],
        [22]]]), array([[[ 5],
        [11]],

       [[17],
        [23]]])]
[array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[12, 13, 14],
        [18, 19, 20]]]), array([[[ 3,  4,  5],
        [ 9, 10, 11]],

       [[15, 16, 17],
        [21, 22, 23]]])]
[array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[12, 13, 14],
        [18, 19, 20]]]), array([[[ 3,  4,  5],
        [ 9, 10, 11]],

       [[15, 16, 17],
        [21, 22, 23]]])]


In [117]:
print(np.dsplit(x, [2, 4, 5]))
print(np.dsplit(x, 4))

[array([[[ 0,  1],
        [ 6,  7]],

       [[12, 13],
        [18, 19]]]), array([[[ 2,  3],
        [ 8,  9]],

       [[14, 15],
        [20, 21]]]), array([[[ 4],
        [10]],

       [[16],
        [22]]]), array([[[ 5],
        [11]],

       [[17],
        [23]]])]


ValueError: array split does not result in an equal division

In [118]:
rg = np.random.default_rng(12345)
print(rg)

Generator(PCG64)


In [119]:
r = rg.random()
print(r)
print(rg.random(5))
print(rg.random((4, 3)))

0.22733602246716966
[0.31675834 0.79736546 0.67625467 0.39110955 0.33281393]
[[0.59830875 0.18673419 0.67275604]
 [0.94180287 0.24824571 0.94888115]
 [0.66723745 0.09589794 0.44183967]
 [0.88647992 0.6974535  0.32647286]]


In [120]:
rg = np.random.default_rng(12345)
r = rg.integers(low = 0, high = 10, size = 3)
print(r)
print(rg.integers(1, 7, (3, 4)))

[6 2 7]
[[2 2 5 4]
 [5 6 3 6]
 [2 4 4 2]]


In [121]:
rg = np.random.default_rng(seed = 42)
print(rg.standard_normal(10))
print(rg.standard_normal((4, 3)))

[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259 -0.01680116 -0.85304393]
[[ 0.87939797  0.77779194  0.0660307 ]
 [ 1.12724121  0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826   0.8784503 ]
 [-0.04992591 -0.18486236 -0.68092954]]


# 배열 결합 연습

In [123]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)

print(np.vstack((a, b, c)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [149]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)

print(np.hstack((p, q, r)))
print(np.column_stack((p, q, r)))
print(np.concatenate((p, q, r)))
print(np.concatenate((p, q, r), axis = 1))
print(np.concatenate((p, q, r), axis = None))
print(np.concatenate((p, q, r), axis = -1))

[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]]
[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]]
[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]
 [21 22 23]
 [24 25 26]]
[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]]
[ 1  2  3  4  5  6 11 12 13 14 15 16 21 22 23 24 25 26]
[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]]
